app = "xvx-vaultwarden"
kill_signal = "SIGINT"
kill_timeout = "5s"
primary_region = "hkg"

[build]
image = "ghcr.io/webees/vaultwarden"

[checks.health]
grace_period = "30s"
interval = "15s"
method = "get"
path = "/alive"
port = 80
timeout = "10s"
type = "http"

[http_service]
force_https = true
internal_port = 80
min_machines_running = 1

[[mounts]]
destination = "/data"
source = "app_data"
